### ISSUE TITLE
Annotation_col and annotation_row colors to change in your script

### ISSUE THREAD

**Issue by shruti3009** [eacton/Heatmaps#1]
Hi, Could you please suggest a way to change the colors for the annotations present in CSV files, that can be incorporated into the script that you have used here for pheatmap?

**Comment by eacton** [comment]
@shruti3009  Thanks for your question. I'll explain the basics here, and then add a section to the pheatmap code, as I'm sure it's something people are interested in customizing. 

pheatmap has an argument called 'annotation_colors', which we will use. We make a list that that will specify our annotation categories (from annotation_col) and which colors we want each of our subtypes to be.  For example, for the annotation of cell type ('Type'), we specify B-cell will be cornflower blue, and T-cell will be orange. We need the brackets around the names of the subtypes in the code below, because they have special characters (-, =).  The same thing is done for Exposure. Then this list is matched to the 'annotation_colors' argument in the pheatmap() function call below.

 
     annotation_colors <- list(
       Type = c('B-cell'="cornflowerblue", 'T-cell'="orange"),
       Exposure = c('X=0'="yellow", 'X=1'="red"))

     pheatmap(genes, cluster_rows = T, cluster_cols = F, annotation_row = annotation_row, annotation_col 
    = annotation_col, annotation_colors = annotation_colors)

Hope that helps!
